### ISSUE TITLE
Error in evalution

### ISSUE THREAD

**Issue by Legitao** [AI-nstein/hoppity#4]
Hi there,

I run into a few problems when running [Finding the Best Model](https://github.com/AI-nstein/hoppity#finding-the-best-model) section.

1. In the README, it says 
> Run find_best_model.sh to start the evaluation

Did you mean [find_no_op_model.sh?](https://github.com/AI-nstein/hoppity/blob/master/gtrans/eval/find_no_op_model.sh)

2. In find_best_model.py, the line [loading vocabulary](https://github.com/AI-nstein/hoppity/blob/5123a328d685c7c3022da094b435f11d097fee03/gtrans/eval/find_best_model.py#L12) tries to load vocab_fixes.npy/vocab_full.npy. However, this file doesn't exist since the result of running run_build_dataset.sh would only save the vocabulary to a file with the name vocab.npy[(code)](https://github.com/AI-nstein/hoppity/blob/5123a328d685c7c3022da094b435f11d097fee03/gtrans/data_process/main_build_dataset.py#L147). Could you elaborate on what the fixes and full vocab are and what this vocab.npy should be?

3. If I use the vocab.npy to fix the file not existing problem above, then there was an error raised when loading the trained model(*.ckpt). The error message is: 

> Traceback (most recent call last):
  File "find_best_model.py", line 57, in <module>
    model.load_state_dict(torch.load(_dir))
  File "/Users/zhutao/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GraphTrans:
	Missing key(s) in state_dict: "bilin.weight", "bilin.bias", "ops.1.bilin.weight", "ops.1.bilin.bias", "ops.2.bilin.weight", "ops.2.bilin.bias", "ops.3.bilin.weight", "ops.3.bilin.bias", "ops.4.bilin.weight", "ops.4.bilin.bias".

Does anyone know the reason?

**Comment by Hanjun-Dai** [comment]
Hi,

It seems for the 3. issue, the training and evaluation architectures are different. It seems you are using 'comp_method bilinear'  when evaluating, but the default config in training script is 'mlp'.

**Comment by elizabethdinella** [comment]
Hi, 

1. Yes, I've changed the filename and pushed. 
2. The vocab of values can be creating in two ways 
     * `Full`: The top 5k values from the entire AST
     * `Fixes`: The top 5k values from the edits. 

The code was ambiguous so I fixed it and pushed. Let me know if you have any other questions. 
In our paper we used the `fixes` vocab type. 
- Elizabeth

**Comment by elizabethdinella** [comment]
Hi Hanjun,

Thanks for your help. I updated the `find_best_model.sh` script to use mlp comp method

**Comment by Legitao** [comment]
Hi @Hanjun-Dai and @elizabethdinella 

Thank you for your quick response.
For 3, I run `find_best_model.sh` with `-comp_method mlp`. But unfortunately, it again showed similar error when loading the trained model:
> Traceback (most recent call last):
  File "find_best_model.py", line 56, in <module>
    model.load_state_dict(torch.load(_dir))
  File "/Users/zhutao/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GraphTrans:
	Missing key(s) in state_dict: "pred.main.0.weight", "pred.main.0.bias", "pred.main.2.weight", "pred.main.2.bias", "pred.main.4.weight", "pred.main.4.bias", "ops.1.pred.main.0.weight", "ops.1.pred.main.0.bias", "ops.1.pred.main.2.weight", "ops.1.pred.main.2.bias", "ops.1.pred.main.4.weight", "ops.1.pred.main.4.bias", "ops.2.pred.main.0.weight", "ops.2.pred.main.0.bias", "ops.2.pred.main.2.weight", "ops.2.pred.main.2.bias", "ops.2.pred.main.4.weight", "ops.2.pred.main.4.bias", "ops.3.pred.main.0.weight", "ops.3.pred.main.0.bias", "ops.3.pred.main.2.weight", "ops.3.pred.main.2.bias", "ops.3.pred.main.4.weight", "ops.3.pred.main.4.bias", "ops.4.pred.main.0.weight", "ops.4.pred.main.0.bias", "ops.4.pred.main.2.weight", "ops.4.pred.main.2.bias", "ops.4.pred.main.4.weight", "ops.4.pred.main.4.bias".

**Comment by elizabethdinella** [comment]
Hi, I updated the `find_best_model.sh` script. Let me know if you still have problems.

**Comment by Legitao** [comment]
Hi Dinella,

I still have the same error message. Is it because I was training with cpu?

**Comment by elizabethdinella** [comment]
I was also training with CPU so I don't think that is the source of the problem.

Can you share your exact parameters of the training and evaluation scripts?

- Elizabeth

**Comment by Legitao** [comment]
I used the exact parameter as you provided:
run_main.sh
> cooked_root=/Users/zhutao/lab/data/small_astPKL
data_name=tttttzzz
save_dir=/Users/zhutao/lab/data/small_trainingResult
python main_gtrans.py \
	-data_root $cooked_root \
	-data_name $data_name \
	-save_dir $save_dir \
	-gnn_type 's2v_multi' \
	-max_lv 4 \
	-max_modify_steps 1 \
	-resampling True \
	-comp_methd "mlp" \
	$@

find_best_model.sh

> data_name=tttttzzz
cooked_root=/Users/zhutao/lab/data/small_astPKL
save_dir=/Users/zhutao/lab/data/small_trainingResult/
loss_file=/Users/zhutao/lab/data/small_trainingResult/OUTPUT_FILE
max_num_diffs=1
export CUDA_VISIBLE_DEVICES=1
python find_best_model.py \
               -data_root $cooked_root \
               -data_name $data_name \
               -save_dir $save_dir \
               -gnn_type 's2v_multi' \
               -loss_file $loss_file \
               -max_lv 4 \
               -max_modify_steps $max_num_diffs \
               -resampling True \
               -comp_method mlp \
               $@

**Comment by elizabethdinella** [comment]
Solved in the most recent commit. The bug was a misspelling of cmp_method.
